name: ETL unit tests

on:
  push:
    paths:
      - 'etl/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.10"

      - name: Install dependencies and run tests
        working-directory: ./etl
        run: |
          pip install pipenv pytest
          pipenv install '-e .'
          pipenv run pytest
