name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: test

    steps:
      - shell: bash
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
        run: |
          echo "$MY_NAME"